# Site settings
title: Stator Theme for Jekyll
tag_text: Stator
description: Stator is a single-page responsive Jekyll theme. This is the most simple and still-good-looking Jekyll theme that you can find.
# baseurl: "/blog" # the subpath of your site, e.g. /blog
# url: "https://example.com" # the base hostname & protocol for your site, e.g. http://example.com

# To use Stator as a remote theme
# remote-theme: sblisesivdin/stator

plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
