# Site settings
title: Stator Theme for Jekyll
tag_text: Stator
description: Stator is a single-page responsive Jekyll theme. This is the most simple and still-good-looking Jekyll theme that you can find.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
